# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: # Replace with a single Polar username
buy_me_a_coffee: # Replace with a single Buy Me a Coffee username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']

I clicked Enable Sponsorships and don't have time for this right now... 

Contact me on X or if your balls/brains are just out-of-control optimized for life, create a free account on https://joywrite.ai/motivated-pilot-application and click that link until you get to the secret fully-refundable deposit page to book time with me. $how me you're serious, and I'll show you what's possible. I am NOT working directly with companies outside the top 3-4 in their market, ideally another #1 or two who I can just lock-in with and secure another 20 years reign soaking up the lion's share of your TAM with. 

Lmao FUNDING.yml, complete. For now. 🤣
